# Generated by Django 5.1.4 on 2026-08-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='module_permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
