# Generated by Django 5.1.4 on 2026-08-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Lead de demonstração — pode ser removido em massa no dashboard.'),
        ),
    ]
