# Generated by Django 5.1.4 on 2026-08-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_cardemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardemailmessage',
            name='is_bounce',
            field=models.BooleanField(default=False),
        ),
    ]
