import type { LucideIcon } from "lucide-react";
import {
  CalendarDays,
  UserRound,
  Clapperboard,
  Handshake,
  Sparkles,
  Mic2,
  Ticket,
  MapPin,
  Star,
  Heart,
  Music,
  PartyPopper,
  Laugh,
  Theater,
  Camera,
  Video,
  Play,
  Film,
  Megaphone,
  Phone,
  Mail,
  MessageCircle,
  Send,
  Rocket,
  Zap,
  Crown,
  Trophy,
  Flame,
  Gift,
  Coffee,
  Wine,
  GlassWater,
  Guitar,
  Headphones,
  Radio,
  Podcast,
  Users,
  User,
  Building2,
  Briefcase,
  Calendar,
  CalendarCheck,
  CalendarRange,
  Clock,
  Timer,
  Compass,
  Home,
  Info,
  HelpCircle,
  BookOpen,
  Newspaper,
  Image,
  Images,
  Aperture,
  Spotlight,
  Wand2,
  Diamond,
  Gem,
  BadgeCheck,
  CircleDot,
  ArrowRightCircle,
  ExternalLink,
  Link2,
  ShoppingCart,
  Store,
  Landmark,
  Flag,
  Globe,
  Navigation,
  Target,
  Crosshair,
  Layers,
  LayoutGrid,
  Menu,
  List,
  CheckCircle2,
  ThumbsUp,
  Smile,
  Sun,
  Moon,
  CloudSun,
} from "lucide-react";

/** Catálogo grande de ícones para o menu público (admin escolhe). */
export const NAV_ICON_OPTIONS: {
  id: string;
  label: string;
  Icon: LucideIcon;
}[] = [
  { id: "calendar-days", label: "Calendário", Icon: CalendarDays },
  { id: "calendar", label: "Agenda", Icon: Calendar },
  { id: "calendar-check", label: "Confirmado", Icon: CalendarCheck },
  { id: "calendar-range", label: "Período", Icon: CalendarRange },
  { id: "clock", label: "Relógio", Icon: Clock },
  { id: "timer", label: "Timer", Icon: Timer },
  { id: "ticket", label: "Ingresso", Icon: Ticket },
  { id: "map-pin", label: "Local", Icon: MapPin },
  { id: "navigation", label: "Navegação", Icon: Navigation },
  { id: "compass", label: "Bússola", Icon: Compass },
  { id: "globe", label: "Mundo", Icon: Globe },
  { id: "flag", label: "Bandeira", Icon: Flag },
  { id: "user-round", label: "Perfil", Icon: UserRound },
  { id: "user", label: "Usuário", Icon: User },
  { id: "users", label: "Pessoas", Icon: Users },
  { id: "clapperboard", label: "Claquete", Icon: Clapperboard },
  { id: "video", label: "Vídeo", Icon: Video },
  { id: "play", label: "Play", Icon: Play },
  { id: "film", label: "Cinema", Icon: Film },
  { id: "camera", label: "Câmera", Icon: Camera },
  { id: "aperture", label: "Lente", Icon: Aperture },
  { id: "image", label: "Imagem", Icon: Image },
  { id: "images", label: "Galeria", Icon: Images },
  { id: "handshake", label: "Acordo", Icon: Handshake },
  { id: "briefcase", label: "Negócios", Icon: Briefcase },
  { id: "building-2", label: "Empresa", Icon: Building2 },
  { id: "landmark", label: "Teatro", Icon: Landmark },
  { id: "store", label: "Loja", Icon: Store },
  { id: "shopping-cart", label: "Carrinho", Icon: ShoppingCart },
  { id: "sparkles", label: "Brilho", Icon: Sparkles },
  { id: "star", label: "Estrela", Icon: Star },
  { id: "crown", label: "Coroa", Icon: Crown },
  { id: "trophy", label: "Troféu", Icon: Trophy },
  { id: "diamond", label: "Diamante", Icon: Diamond },
  { id: "gem", label: "Joia", Icon: Gem },
  { id: "flame", label: "Chama", Icon: Flame },
  { id: "zap", label: "Raio", Icon: Zap },
  { id: "rocket", label: "Foguete", Icon: Rocket },
  { id: "wand-2", label: "Mágica", Icon: Wand2 },
  { id: "spotlight", label: "Holofote", Icon: Spotlight },
  { id: "mic-2", label: "Microfone", Icon: Mic2 },
  { id: "music", label: "Música", Icon: Music },
  { id: "guitar", label: "Guitarra", Icon: Guitar },
  { id: "headphones", label: "Fone", Icon: Headphones },
  { id: "radio", label: "Rádio", Icon: Radio },
  { id: "podcast", label: "Podcast", Icon: Podcast },
  { id: "theater", label: "Palco", Icon: Theater },
  { id: "laugh", label: "Risada", Icon: Laugh },
  { id: "smile", label: "Sorriso", Icon: Smile },
  { id: "party-popper", label: "Festa", Icon: PartyPopper },
  { id: "gift", label: "Presente", Icon: Gift },
  { id: "heart", label: "Coração", Icon: Heart },
  { id: "thumbs-up", label: "Curtir", Icon: ThumbsUp },
  { id: "megaphone", label: "Megafone", Icon: Megaphone },
  { id: "phone", label: "Telefone", Icon: Phone },
  { id: "mail", label: "E-mail", Icon: Mail },
  { id: "message-circle", label: "Chat", Icon: MessageCircle },
  { id: "send", label: "Enviar", Icon: Send },
  { id: "home", label: "Início", Icon: Home },
  { id: "info", label: "Info", Icon: Info },
  { id: "help-circle", label: "Ajuda", Icon: HelpCircle },
  { id: "book-open", label: "Livro", Icon: BookOpen },
  { id: "newspaper", label: "Notícia", Icon: Newspaper },
  { id: "badge-check", label: "Verificado", Icon: BadgeCheck },
  { id: "check-circle-2", label: "Ok", Icon: CheckCircle2 },
  { id: "target", label: "Alvo", Icon: Target },
  { id: "crosshair", label: "Mira", Icon: Crosshair },
  { id: "layers", label: "Camadas", Icon: Layers },
  { id: "layout-grid", label: "Grade", Icon: LayoutGrid },
  { id: "menu", label: "Menu", Icon: Menu },
  { id: "list", label: "Lista", Icon: List },
  { id: "circle-dot", label: "Ponto", Icon: CircleDot },
  { id: "arrow-right-circle", label: "Avançar", Icon: ArrowRightCircle },
  { id: "external-link", label: "Link externo", Icon: ExternalLink },
  { id: "link-2", label: "Link", Icon: Link2 },
  { id: "coffee", label: "Café", Icon: Coffee },
  { id: "wine", label: "Vinho", Icon: Wine },
  { id: "glass-water", label: "Copo", Icon: GlassWater },
  { id: "sun", label: "Sol", Icon: Sun },
  { id: "moon", label: "Lua", Icon: Moon },
  { id: "cloud-sun", label: "Clima", Icon: CloudSun },
];

const ICON_MAP = Object.fromEntries(
  NAV_ICON_OPTIONS.map((o) => [o.id, o.Icon])
) as Record<string, LucideIcon>;

export function resolveNavIcon(id?: string | null, fallback = "sparkles"): LucideIcon {
  if (id && ICON_MAP[id]) return ICON_MAP[id];
  return ICON_MAP[fallback] || Sparkles;
}

export type NavMenuConfig = {
  nav_cta?: string;
  nav_icon_cta?: string;
  nav_label_agenda?: string;
  nav_icon_agenda?: string;
  nav_label_sobre?: string;
  nav_icon_sobre?: string;
  nav_label_video?: string;
  nav_icon_video?: string;
  nav_label_contato?: string;
  nav_icon_contato?: string;
};

export function buildNavLinks(cfg?: NavMenuConfig | null) {
  return [
    {
      href: "#agenda",
      label: cfg?.nav_label_agenda?.trim() || "Agenda",
      iconId: cfg?.nav_icon_agenda || "calendar-days",
    },
    {
      href: "#sobre",
      label: cfg?.nav_label_sobre?.trim() || "Sobre",
      iconId: cfg?.nav_icon_sobre || "user-round",
    },
    {
      href: "#video",
      label: cfg?.nav_label_video?.trim() || "Vídeo",
      iconId: cfg?.nav_icon_video || "clapperboard",
    },
    {
      href: "#contato",
      label: cfg?.nav_label_contato?.trim() || "Contratação",
      iconId: cfg?.nav_icon_contato || "handshake",
    },
  ] as const;
}
