# Generated by Django 5.1.4 on 2026-08-07 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Rafael Aragão', max_length=200)),
                ('hero_subtitle', models.CharField(default='Rei dos Peão — Humorista', max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_image_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#f5b301', max_length=20)),
                ('secondary_color', models.CharField(default='#0f0f0f', max_length=20)),
                ('about_title', models.CharField(default='Sobre o Artista', max_length=200)),
                ('about_text', models.TextField(blank=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('about_image_url', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('spotify', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('footer_text', models.CharField(blank=True, max_length=300)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('og_image_url', models.URLField(blank=True)),
                ('hide_rule', models.CharField(choices=[('immediate', 'Imediatamente após o evento'), ('next_day', '1 dia depois'), ('days_after', 'X dias após o encerramento')], default='next_day', max_length=20)),
                ('hide_days_after', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do site',
                'verbose_name_plural': 'Configuração do site',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Criação'), ('update', 'Edição'), ('delete', 'Exclusão'), ('login', 'Login'), ('move', 'Movimentação')], max_length=20)),
                ('model_name', models.CharField(max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
