# Generated by Django 5.1.4 on 2026-08-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='demo_data_active',
            field=models.BooleanField(default=False),
        ),
    ]
