# Generated by Django 5.1.4 on 2026-08-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_perms_and_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='about_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='facebook',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='instagram',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='og_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='spotify',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='tiktok',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='youtube',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
